namespace: ""

# helmCharts:
#     # The name field is optional and not recommended to use (better use namePrefix or nameSuffix).
#   - name: whoami-test
#     repo: https://cowboysysop.github.io/charts/
#     chart: whoami
helmCharts: []

# middlewares:
#     # The name field is optional and not recommended to use (better use namePrefix or nameSuffix).
#   - name: redirect-to-non-www
#     redirectRegex:
#       regex: ^https?://www.(.*)
#       replacement: https://${1}
#       permanent: true
#     headers:
#       customRequestHeaders:
#         X-Forwarded-Proto: "https"
middlewares: []

# ingressRoutes:
#     # The name field is optional and not recommended to use (better use namePrefix or nameSuffix).
#   - name: whoami-test-route
#     entryPoints:
#       - websecure
#     routes:
#       - kind: Rule
#         match: Host(`whoami.example.com`)
#         middlewares:
#           # An empty name will be replace by the release name of the helm chart.
#           # That's especially useful when there's only one middleware and no "name", "namePrefix" and "nameSuffix" is provided.
#           # "name", "namePrefix" and "nameSuffix" are available here as well (like with all the other "name" fields in this chart).
#           - name: ""
#         services:
#             # The "name" field is optional. If no name is provided the release name will be used.
#             # "namePrefix" and "nameSuffix" are working as well and will be prefixed / suffixed to the release name.
#           - name: whoami-test
#             port: 80
#     tls:
#       certResolver: letsencrypt
#       domains:
#         - main: whoami.example.com
#           sans:
#             - dev.whoami.example.com
ingressRoutes: []
