apiVersion: v2
appVersion: 0.10.6
description: Helm chart wrapper around the Helm Controller HelmChart CRD and the Traefik CRD resources
engine: gotpl
home: https://github.com/humiu/charts/tree/main/charts/traefik-helmchart-wrapper
keywords:
  - helm
  - helm-controller
  - helmchart
  - traefik
  - ingressroute
maintainers:
  - name: Paul Miu
    email: paul@humiu.io
name: traefik-helmchart-wrapper
sources:
  - https://github.com/k3s-io/helm-controller
  - https://github.com/traefik/traefik-helm-chart
version: 0.5.0
