# The namespace in which the resources will be installed.
# You can't use the `--namespace` flag on `helm install` because the helm controller requires the "HelmChart" CRD(s) to be installed in the
# "kube-system" namespace and using the `--namespace` flag would prevent a multi namespace installation and the installation would fail.
namespace:
  # The "name" field is optional. If empty or not provided the helm release name will be used instead.
  # Instead of providing the full namespace you can also use "namePrefix" or "nameSuffix" to use the helm release name and prefix and/or suffix.
  name: ""
  # The "create" property defines whether to create the namespace or not.
  # Can always be enabled ("true") since this chart automatically recognizes if the namespace already exists or not.
  # This setting is only necessary when using this chart as a subchart of another helm chart.
  create: true
  # The "resourcePolicy" field is optional. If it's set to "keep" the namespace WILL NOT be deleted when the chart is being uninstalled.
  # If resourcePolicy is set to an empty string ("") the namespace WILL BE DELETED on uninstall! Only do this if your helm chart is the
  # only application in this namespace or when you're 100% sure that you want to delete all other resources in this namespace as well!
  resourcePolicy: keep

# Helm Controller HelmChart (https://rancher.com/docs/k3s/latest/en/helm/#using-the-helm-crd)
# helmCharts:
#     # The "name" field is optional and not recommended to use (better use "namePrefix" or "nameSuffix").
#   - name: whoami-test
#     repo: https://cowboysysop.github.io/charts/
#     chart: whoami
#     version: 2.5.0
#     values:
#       replicaCount: 2
#       podLabels:
#         "env": "test"
#       ingress:
#         enabled: false
helmCharts: []

# The following configurations will generate Traefik CRD resources.
# Here are lots of examples on how to configure them:
# https://doc.traefik.io/traefik/reference/dynamic-configuration/kubernetes-crd/#resources
traefik:
  # Traefik Middleware (https://doc.traefik.io/traefik/middlewares/overview/)
  # middlewares:
  #     # The "name" field is optional and not recommended to use (better use "namePrefix" or "nameSuffix").
  #   - name: redirect-to-non-www
  #     redirectRegex:
  #       regex: ^https?://www.(.*)
  #       replacement: https://${1}
  #       permanent: true
  #     headers:
  #       customRequestHeaders:
  #         X-Forwarded-Proto: "https"
  middlewares: []

  # Traefik ServersTransport (https://doc.traefik.io/traefik/routing/overview/#transport-configuration)
  # serversTransports:
  #     # The "name" field is optional and not recommended to use (better use "namePrefix" or "nameSuffix").
  #   - name: mytransport
  #     serverName: foobar
  #     insecureSkipVerify: true
  #     rootCAsSecrets:
  #       - foobar
  #     certificatesSecrets:
  #       - foobar
  #     maxIdleConnsPerHost: 1
  #     forwardingTimeouts:
  #       dialTimeout: 42s
  #       responseHeaderTimeout: 42s
  #       idleConnTimeout: 42s
  #     disableHTTP2: true
  serversTransports: []

  # Traefik IngressRoute (https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroute)
  # ingressRoutes:
  #     # The "name" field is optional and not recommended to use (better use "namePrefix" or "nameSuffix").
  #   - name: whoami-test-route
  #     entryPoints:
  #       - websecure
  #     routes:
  #       - kind: Rule
  #         match: Host(`whoami.example.com`)
  #         middlewares:
  #           # An empty name will be replaced by the release name of the helm chart.
  #           # That's especially useful when there's only one middleware and no "name", "namePrefix" and "nameSuffix" is provided.
  #           # "name", "namePrefix" and "nameSuffix" are available here as well (like with all the other "name" fields in this chart).
  #           - name: ""
  #         services:
  #             # The "name" field is optional. If no name is provided the release name will be used.
  #             # "namePrefix" and "nameSuffix" are working as well and will be prefixed / suffixed to the release name.
  #           - name: whoami-test
  #             port: 80
  #             # The "serversTransport" field is optional and maximum one serversTransport can be added per service.
  #             # CAUTION: This is different from the official Traefik implementation! Because the name cannot be specified directly
  #             # as value of "serversTransport" but must be a child of either "name", "namePrefix" or "nameSuffix"!
  #             # The only exception is if the "serversTransport" value is an empty string.
  #             # In that case the value will be replaced by the release name of the helm chart.
  #             serversTransport:
  #               name: test-it
  #     tls:
  #       certResolver: letsencrypt
  #       domains:
  #         - main: whoami.example.com
  #           sans:
  #             - dev.whoami.example.com
  ingressRoutes: []
