
{{ range .Values.helmCharts }}

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: {{ template "name" ( dict "resource" . "Release" $.Release ) }}
  namespace: kube-system
spec:
  {{- if .repo }}
  repo: {{ .repo | quote }}
  {{- end }}
  chart: {{ .chart | quote }}
  {{- if .version }}
  version: {{ .version | quote }}
  {{- end }}
  targetNamespace: {{ template "namespace" $ }}
  {{- if .values }}
  valuesContent: |
    {{- toYaml .values | nindent 4 }}
  {{- end }}

{{ end }}

