
{{ range .Values.traefik.middlewares }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ template "name" ( dict "value" . "context" $ ) }}
  namespace: {{ template "namespace" $ }}
spec:
  {{- omit . "name" "namePrefix" "nameSuffix" | toYaml | nindent 2 }}

{{ end }}
