apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: "{{ template "name.unquoted" ( dict "value" . "context" $ ) }}-installer"
  namespace: {{ .Release.Namespace | quote }}
spec:
  repo: https://charts.gitlab.io
  chart: gitlab-runner
  {{- if .Values.gitlabRunnerHelmchartVersion }}
  version: {{ .Values.gitlabRunnerHelmchartVersion | quote }}
  {{- end }}
  targetNamespace: {{ template "namespace" $ }}
  valuesContent: |
    {{- toYaml .Values.gitlabRunnerValues | nindent 4 }}
