apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-admin
  namespace: {{ .Release.Namespace | quote }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: gitlab-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: gitlab-admin
    namespace: {{ .Release.Namespace | quote }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner
  namespace: {{ .Release.Namespace | quote }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-runner-manager
  namespace: {{ .Release.Namespace | quote }}
rules:
  - apiGroups: ["", "batch", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-runner-binding
  namespace: {{ .Release.Namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: gitlab-runner
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: gitlab-runner-manager
  apiGroup: rbac.authorization.k8s.io