
{{ range .Values.ingressRoutes }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .name | default ( print ( .namePrefix | default "" ) $.Release.Name ( .nameSuffix | default "" ) ) | quote }}
  namespace: {{ $.Values.namespace | quote }}
spec:
  {{- if .entryPoints }}
  entryPoints: {{ toYaml .entryPoints | nindent 4 }}
  {{- end }}
  routes:
    {{- range .routes }}
    - {{- omit . "services" "middlewares" | toYaml | nindent 6 }}
      {{- if .middlewares }}
      middlewares:
        {{- range .middlewares }}
        - name: {{ .name | default ( print ( .namePrefix | default "" ) $.Release.Name ( .nameSuffix | default "" ) ) | quote }}
        {{- end }}
      {{- end }}
      {{- if .services }}
      services:
        {{- range .services }}
        - {{ omit . "name" "namePrefix" "nameSuffix" "serversTransport" | toYaml | nindent 10 }}
          name: {{ .name | default ( print ( .namePrefix | default "" ) $.Release.Name ( .nameSuffix | default "" ) ) | quote }}
          {{- if .serversTransport }}
          serversTransport: {{ .serversTransport.name | default ( print ( .serversTransport.namePrefix | default "" ) $.Release.Name ( .serversTransport.nameSuffix | default "" ) ) | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- if .tls }}
  tls: {{ toYaml .tls | nindent 4 }}
  {{- end }}

{{ end }}

