
{{ if not ( lookup "v1" "Namespace" "" ( .Values.namespace ) ) }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | quote }}
  annotations:
    "helm.sh/resource-policy": keep

{{ end }}
