
{{ range .Values.traefik.serversTransports }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: {{ template "name" ( dict "resource" . "Release" $.Release ) }}
  namespace: {{ template "namespace" $ }}
spec:
  {{- omit . "name" "namePrefix" "nameSuffix" | toYaml | nindent 2 }}

{{ end }}
