
{{- with .Values }}

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: {{ print $.Release.Name "-wordpress" | quote }}
  namespace: kube-system
spec:
  repo: https://humiu.github.io/charts
  chart: traefik-helmchart-wrapper
  version: {{ .traefikHelmchartWrapper.version | quote }}
  targetNamespace: kube-system
  valuesContent: |

    namespace:
      name: {{ template "namespace" $ }}

    helmCharts:
      {{- range .environments }}
      - nameSuffix: -{{ .name }}
        repo: https://humiu.github.io/charts
        chart: wordpress-nginx-cache
        values:
          wordpress:
            fullnameOverride: {{ print $.Release.Name "-wordpress-" .name | quote }}
            {{- toYaml $.Values.wordpressValues | nindent 12 }}
          mariadb:
            fullnameOverride: {{ print $.Release.Name "-mariadb-" .name | quote }}
      {{- end }}

    traefik:
      ingressRoutes:
        {{- range .environments }}
        {{- $subdomain := ( empty .subdomain ) | ternary "" ( print .subdomain "." ) }}
        {{- $domain := print $subdomain $.Values.domain.main }}
        {{- $aliases := "" }}
        {{- $nocacheAliases := "" }}
        {{- range $.Values.domain.aliases }}
        {{- $aliases = print $aliases " || HostRegexp(`{host:(www.)?}" $subdomain . "`)" }}
        {{- $nocacheAliases = print $nocacheAliases " || HostRegexp(`{host:(www.)?}nocache." $subdomain . "`)" }}
        {{- end }}
        - nameSuffix: -{{ .name }}
          entryPoints:
            - websecure
          routes:
            - kind: Rule
              match: "HostRegexp(`{host:(www.)?}{{ $domain }}`){{ $aliases }}"
              middlewares:
                - nameSuffix: "-redirect-www"
              services:
                - nameSuffix: -{{ .name }}
                  port: 9090
                  scheme: https
                  serversTransport:
                    nameSuffix: -no-cert-check
            - kind: Rule
              match: "HostRegexp(`{host:(www.)?}nocache.{{ $domain }}`){{ $nocacheAliases }}"
              middlewares:
                - nameSuffix: "-redirect-www"
              services:
                - nameSuffix: -{{ .name }}
                  port: 443
                  scheme: https
                  serversTransport:
                    nameSuffix: -no-cert-check
          tls:
            certResolver: letsencrypt
            domains:
              - main: "{{ $domain }}"
                sans:
                  - {{ print "nocache." $domain | quote }}
                  {{- range $.Values.domain.aliases }}
                  - {{ print $subdomain . | quote }}
                  - {{ print "nocache." $subdomain . | quote }}
                  {{- end }}
        {{- end }}

      middlewares:
        - nameSuffix: -redirect-www
          redirectRegex:
            regex: ^https?://www.(.*)
            replacement: https://${1}
            permanent: true

      serversTransports:
        - nameSuffix: -no-cert-check
          insecureSkipVerify: true

{{- end }}
