
{{- if empty ( lookup "v1" "Namespace" "" ( include "namespace.unquoted" $ ) ) }}
{{- with .Values.namespace }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ template "namespace" $ }}
  {{- if .resourcePolicy }}
  annotations:
    "helm.sh/resource-policy": {{ .resourcePolicy }}
  {{- end }}

{{- end }}
{{- end }}
